<?php

declare(strict_types=1);

namespace BastianSchwabe\Jobs\Middleware;

use BastianSchwabe\Jobs\Service\Tracking\SessionHashResolver;
use BastianSchwabe\Jobs\Service\Tracking\TrackingService;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use Psr\Http\Server\RequestHandlerInterface;
use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerAwareTrait;
use TYPO3\CMS\Core\Routing\PageArguments;

/**
 * Counts job detail views.
 *
 * The detail plugin is cacheable, so its controller only runs on a cache miss.
 * A middleware sees every request, cached or not. It reads the job argument
 * the route enhancer already decoded and counts once the page was delivered
 * successfully, so 404s and redirects leave no trace.
 */
final class JobViewTracker implements MiddlewareInterface, LoggerAwareInterface
{
    use LoggerAwareTrait;

    /** Plugin namespace of the detail plugin, as generated by Extbase. */
    private const PLUGIN_NAMESPACE = 'tx_jobs_show';

    public function __construct(
        private readonly TrackingService $trackingService,
        private readonly SessionHashResolver $sessionHashResolver,
    ) {}

    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $jobUid = $this->extractRequestedJob($request);
        if ($jobUid === null) {
            return $handler->handle($request);
        }

        $response = $handler->handle($request);
        if ($response->getStatusCode() !== 200) {
            return $response;
        }

        try {
            $trackedUid = $this->trackingService->resolveTrackedJobUid($jobUid);
            $sessionHash = $trackedUid === null ? null : $this->sessionHashResolver->resolve($request);
            if ($trackedUid !== null && $sessionHash !== null) {
                $this->trackingService->trackView($trackedUid, $sessionHash);
            }
        } catch (\Throwable $exception) {
            // Statistics must never break page delivery.
            $this->logger?->error('Job view could not be tracked: ' . $exception->getMessage(), ['exception' => $exception]);
        }

        return $response;
    }

    /**
     * The job uid of a detail request, or null for any other request.
     * The "apply" action is excluded: it redirects and is counted separately.
     */
    private function extractRequestedJob(ServerRequestInterface $request): ?int
    {
        $pageArguments = $request->getAttribute('routing');
        if (!$pageArguments instanceof PageArguments) {
            return null;
        }

        $arguments = $pageArguments->getArguments()[self::PLUGIN_NAMESPACE] ?? null;
        if (!is_array($arguments)) {
            return null;
        }

        $action = (string)($arguments['action'] ?? 'show');
        if ($action !== 'show') {
            return null;
        }

        $job = $arguments['job'] ?? null;
        if (!is_numeric($job) || (int)$job <= 0) {
            return null;
        }

        return (int)$job;
    }
}
